# Generated by Django 5.0.4 on 2024-05-28 13:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppProduit', '0006_alter_favorie_date_ajoutf_alter_produit_date_ajout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=datetime.datetime(2024, 5, 28, 16, 29, 6, 617389))),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProduit.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'produit')},
            },
        ),
    ]
