# Generated by Django 5.0.4 on 2024-05-28 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFavorie', '0003_alter_favorie_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorie',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 17, 8, 26, 770464)),
        ),
    ]
