# Generated by Django 5.0.4 on 2024-05-28 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFavorie', '0004_alter_favorie_date_add'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorie',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favorie',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 17, 12, 48, 460084)),
        ),
    ]
