# Generated by Django 5.0.4 on 2024-05-27 16:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Vase', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produit', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProduit.produit', verbose_name='Produit'))),
                ('id_membre', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('notation', models.FloatField(default=0)),
                ('date_ajoutF', models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 21, 5, 513186), verbose_name="Date d'ajout Notation")),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(default='Fer', max_length=64, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProduit.categorie')),
        ),
        migrations.AddField(
            model_name='produit',
            name='lieu',
            field=models.CharField(default='Antananarivo', max_length=128),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 21, 5, 513186)),
        ),
        migrations.AlterField(
            model_name='produit',
            name='materiaux',
            field=models.CharField(default='Vase', max_length=64, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProduit.categorie')),
        ),
    ]
