# Generated by Django 5.0.4 on 2024-05-28 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduit', '0005_alter_categorie_type_alter_favorie_date_ajoutf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorie',
            name='date_ajoutF',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 16, 29, 6, 607859), verbose_name="Date d'ajout Notation"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 16, 29, 6, 607859)),
        ),
    ]
