# Generated by Django 5.0.4 on 2024-05-17 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('addresse', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, verbose_name='Numero de télephone')),
                ('photo', models.ImageField(upload_to='static/img/user', verbose_name='Photo de couverture')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Groupe de privilège')),
                ('pseudo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Pseudo de l'user")),
            ],
        ),
    ]
