# Generated by Django 5.0.4 on 2024-05-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pseudo',
            new_name='user',
        ),
    ]
