# Generated by Django 5.0.4 on 2024-05-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_photo_profile_image_remove_profile_addresse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
