# Generated by Django 5.0.4 on 2024-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='033 33 333 33', max_length=20, unique=True),
        ),
    ]
