# Generated by Django 5.0.4 on 2024-05-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
