# Generated by Django 5.0.4 on 2024-06-04 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbArticle', models.IntegerField()),
                ('sommeTotal', models.IntegerField()),
                ('nom_client', models.TextField()),
                ('prenom_client', models.TextField()),
                ('pseudo_client', models.TextField()),
                ('addresse_client', models.TimeField()),
                ('telephone_client', models.CharField(max_length=64)),
                ('date_commande', models.DateTimeField(default=datetime.datetime(2024, 6, 4, 16, 41, 26, 87598))),
                ('note', models.TextField()),
            ],
        ),
    ]
