# Generated by Django 5.0.4 on 2024-06-04 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCommande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='addresse_client',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 16, 43, 19, 819522)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom_client',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prenom_client',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='commande',
            name='pseudo_client',
            field=models.CharField(max_length=64),
        ),
    ]
